import { SportNode } from '@/types/sports.types';

export const STATIC_SPORTS_SIDEBAR: SportNode[] = [
  {
    id: 'football',
    name: 'Football',
    leagues: [
      {
        id: 'cecafa-kagame-3rd',
        name: 'AFRICA CECAFA KAGAME CUP - 3RD PLACE',
        dates: [
          {
            id: '2026-08-07',
            date: '2026-08-07',
            events: [
              {
                id: 'al-hilal-v-jamus',
                name: 'Al Hilal Omdurman v Jamus FC',
                markets: [
                  { id: 'm-1', name: 'Next Goal 7.0' },
                  { id: 'm-2', name: 'Next Goal 2.0' },
                  { id: 'm-3', name: '2nd Period Winner' },
                  { id: 'm-4', name: 'MATCH_ODDS' },
                  { id: 'm-5', name: 'HT/FT' },
                  { id: 'm-6', name: 'Next Goal 3.0' },
                  { id: 'm-7', name: 'Next Goal 8.0' },
                  { id: 'm-8', name: 'OVER_UNDER_35' },
                  { id: 'm-9', name: 'Next Goal 9.0' },
                  { id: 'm-10', name: 'Next Goal 5.0' },
                  { id: 'm-11', name: 'Next Goal 4.0' },
                  { id: 'm-12', name: 'Draw No Bet' },
                  { id: 'm-13', name: '1st Period Winner' },
                  { id: 'm-14', name: 'Next Goal 6.0' },
                  { id: 'm-15', name: 'OVER_UNDER_15' },
                  { id: 'm-16', name: 'Both Teams To Score' },
                  { id: 'm-17', name: 'OVER_UNDER_25' },
                  { id: 'm-18', name: 'OVER_UNDER_05' },
                  { id: 'm-19', name: 'Next Goal 1.0' },
                ],
              },
              {
                id: 'rayon-v-gor-mahia',
                name: 'Rayon Sports FC v Gor Mahia FC',
              },
            ],
          },
        ],
      },
      { id: 'cecafa-final', name: 'AFRICA CECAFA KAGAME CUP - FINAL' },
      { id: 'arg-primera-b', name: 'ARGENTINA  Primera B' },
      { id: 'arg-liga-profesional', name: 'ARGENTINA Liga Profesional' },
      { id: 'arg-nacional-reserve', name: 'ARGENTINA Nacional Reserve League' },
      { id: 'arg-reserve-league', name: 'ARGENTINA Reserve League' },
      { id: 'asia-asean-champ', name: 'ASIA ASEAN Championship' },
      { id: 'aus-n-nsw-premier-women', name: 'AUSTRALIA  Northern NSW Premier League Women' },
      { id: 'aus-npl-qld-women', name: 'AUSTRALIA  NPL Queensland Women' },
      { id: 'aus-npl-sa', name: 'AUSTRALIA  NPL South Australia' },
      { id: 'aus-darwin-premier', name: 'AUSTRALIA Darwin Premier League' },
      { id: 'aus-nsw-league-2', name: 'AUSTRALIA New South Wales League 2' },
      { id: 'aus-npl-qld', name: 'AUSTRALIA NPL Queensland' },
      { id: 'aus-npl-vic-women', name: 'AUSTRALIA NPL Victoria Women' },
      { id: 'aus-nsw-league-1-u20', name: 'AUSTRALIA NSW  League 1 U20' },
      { id: 'aus-nsw-league-1', name: 'AUSTRALIA NSW League One' },
      { id: 'aus-sa-premier-women-res', name: 'AUSTRALIA SA Premier League  Women Reserves' },
      { id: 'aus-sa-premier-women', name: 'AUSTRALIA SA Premier League Women' },
      { id: 'aus-sa-state-league', name: 'AUSTRALIA SA State League' },
      { id: 'aus-vic-premier-2', name: 'AUSTRALIA Victoria Premier League 2' },
      { id: 'austria-2-liga', name: 'AUSTRIA 2. Liga' },
      { id: 'austria-bundesliga', name: 'AUSTRIA Bundesliga' },
      { id: 'belgium-jupiler', name: 'BELGIUM Jupiler Pro League' },
      { id: 'bolivia-div-profesional', name: 'BOLIVIA Division Profesional' },
      { id: 'bolivia-liga-femenina', name: 'BOLIVIA Liga Femenina' },
      { id: 'brazil-mineiro-u20', name: 'BRAZIL  Mineiro U20' },
      { id: 'brazil-copa-goias-u20', name: 'BRAZIL Copa Goias  U20' },
      { id: 'brazil-serie-b', name: 'BRAZIL Serie B' },
      { id: 'bulgaria-parva-liga', name: 'BULGARIA Parva liga' },
      { id: 'canada-premier', name: 'CANADA Canadian Premier League' },
      { id: 'chile-liga-ascenso', name: 'CHILE Liga de Ascenso' },
      { id: 'chile-liga-primera', name: 'CHILE Liga de Primera' },
      { id: 'china-super-league', name: 'CHINA Super League' },
      { id: 'colombia-regional-league', name: 'COLOMBIA  Regional League' },
      { id: 'czech-chance-liga', name: 'CZECH REPUBLIC   Chance Liga' },
      { id: 'czech-chnl', name: 'CZECH REPUBLIC ChNL' },
      { id: 'denmark-2nd-div', name: 'DENMARK 2nd Division' },
      { id: 'denmark-superliga', name: 'DENMARK Superliga' },
      { id: 'ecuador-liga-pro', name: 'ECUADOR Liga Pro' },
      { id: 'el-salvador-primera', name: 'EL SALVADOR Primera Division' },
      { id: 'england-efl-cup', name: 'ENGLAND EFL Cup' },
      { id: 'england-fa-community-shield', name: 'ENGLAND FA COMMUNITY SHIELD - FINAL' },
      { id: 'estonia-meistriliiga', name: 'ESTONIA Meistriliiga' },
      { id: 'europe-champions-women-qual', name: 'EUROPE  Champions League Women - Qualification' },
      { id: 'europe-emirates-cup', name: 'EUROPE EMIRATES CUP - FINAL' },
      { id: 'europe-uefa-super-cup', name: 'EUROPE UEFA SUPER CUP - FINAL' },
      { id: 'finland-veikkausliiga', name: 'FINLAND  Veikkausliiga' },
      { id: 'finland-ykkonen', name: 'FINLAND Ykkonen' },
      { id: 'finland-ykkosliiga', name: 'FINLAND Ykkosliiga' },
      { id: 'georgia-erovnuli-liga', name: 'GEORGIA Crystalbet Erovnuli Liga' },
      { id: 'germany-2-bundesliga', name: 'GERMANY 2. Bundesliga' },
      { id: 'germany-3-liga', name: 'GERMANY 3. Liga' },
      { id: 'guatemala-liga-nacional', name: 'GUATEMALA Liga Nacional' },
      { id: 'ireland-div-1', name: 'IRELAND Division 1' },
      { id: 'ireland-premier-div', name: 'IRELAND Premier Division' },
      { id: 'japan-j1-league', name: 'JAPAN J1 League' },
      { id: 'lithuania-1-lyga', name: 'LITHUANIA I Lyga' },
      { id: 'mexico-expansion-mx', name: 'MEXICO  Liga de Expansion MX' },
      { id: 'mozambique-mocambola', name: 'MOZAMBIQUE Mocambola' },
      { id: 'myanmar-u20-league', name: 'MYANMAR U20 League' },
      { id: 'netherlands-eerste', name: 'NETHERLANDS Eerste Divisie' },
      { id: 'netherlands-eredivisie', name: 'NETHERLANDS Eredivisie' },
      { id: 'new-zealand-nrfl-women', name: 'NEW ZEALAND NRFL Premier Division Women' },
      { id: 'north-central-leagues-cup', name: 'NORTH and CENTRAL AMERICA LEAGUES  CUP' },
      { id: 'norway-eliteserien', name: 'NORWAY Eliteserien' },
      { id: 'panama-lpf', name: 'PANAMA LPF' },
      { id: 'paraguay-copa-primera', name: 'PARAGUAY Copa de Primera' },
      { id: 'peru-liga-1', name: 'PERU Liga 1' },
      { id: 'poland-ekstraklasa', name: 'POLAND  Ekstraklasa' },
      { id: 'poland-div-1', name: 'POLAND Division 1' },
      { id: 'portugal-liga-portugal', name: 'PORTUGAL Liga Portugal' },
      { id: 'romania-liga-2', name: 'ROMANIA Liga 2' },
      { id: 'romania-superliga', name: 'ROMANIA Superliga' },
      { id: 'south-korea-k2', name: 'SOUTH KOREA K League 2' },
      { id: 'south-korea-wk-women', name: 'SOUTH KOREA WK League Women' },
      { id: 'sweden-superettan', name: 'SWEDEN Superettan' },
      { id: 'switzerland-challenge', name: 'SWITZERLAND Challenge League' },
      { id: 'testing', name: 'TESTING' },
      { id: 'ukraine-persha-liga', name: 'UKRAINE  Persha Liga' },
      { id: 'uruguay-liga-auf', name: 'URUGUAY Liga AUF Uruguaya' },
      { id: 'uzbekistan-super-league', name: 'UZBEKISTAN  Super League' },
      { id: 'world-club-friendly', name: 'WORLD Club Friendly' },
    ],
  },
  { id: 'tennis', name: 'Tennis' },
  { id: 'mma', name: 'Mixed Martial Arts' },
  { id: 'cricket', name: 'Cricket' },
  { id: 'golf', name: 'Golf' },
  { id: 'boxing', name: 'Boxing' },
  { id: 'beach-volleyball', name: 'Beach Volleyball' },
  { id: 'table-tennis', name: 'Table Tennis' },
  { id: 'futsal', name: 'Futsal' },
  { id: 'horse-racing', name: 'Horse Racing' },
  { id: 'egames', name: 'E Games' },
  { id: 'basketball', name: 'Basketball' },
  { id: 'motogp', name: 'MotoGP' },
  { id: 'chess', name: 'Chess' },
  { id: 'volleyball', name: 'Volleyball' },
  { id: 'ice-hockey', name: 'Ice Hockey' },
  { id: 'badminton', name: 'Badminton' },
  { id: 'cycling', name: 'Cycling' },
  { id: 'motorbikes', name: 'Motorbikes' },
  { id: 'athletics', name: 'Athletics' },
  { id: 'basketball-3x3', name: 'Basketball 3X3' },
  { id: 'sumo', name: 'Sumo' },
  { id: 'virtual-sports', name: 'Virtual sports' },
  { id: 'handball', name: 'Handball' },
  { id: 'politics', name: 'Politics' },
  { id: 'motor-sports', name: 'Motor Sports' },
  { id: 'baseball', name: 'Baseball' },
  { id: 'rugby-union', name: 'Rugby Union' },
  { id: 'rugby-league', name: 'Rugby League' },
  { id: 'darts', name: 'Darts' },
  { id: 'american-football', name: 'American Football' },
  { id: 'snooker', name: 'Snooker' },
  { id: 'soccer', name: 'Soccer' },
  { id: 'esports', name: 'Esports' },
  { id: 'greyhound-racing', name: 'Greyhound Racing' },
  { id: 'kabaddi', name: 'Kabaddi' },
  { id: 'boat-racing', name: 'Boat Racing' },
  { id: 'esoccer', name: 'Esoccer' },
  { id: 'wrestling', name: 'Wrestling' },
];
